- scripts/rockSaw.lua
Updated to find text rather than images and modified the timers to make the more accurate for the current levels of latency.
> rockSaw.lua fix

- scripts/potteryAuto.lua
Pottery macro for making jugs and mortars on a pottery wheel that does not require use of the mouse.
> potteryAuto addition

- scripts/wood.lua
wood.lua - Complete rewrite so it mostly uses OCR.
> Rewrite wood.lua

- scripts/boards.lua
- scripts/wood.lua
boards.lua - rewrite to use only text instead of images, added option to form a grid and to close windows when you exit.
wood.lua - changed safeClicks to clickTexts
> Update to wood.lua and boards.lua

- scripts/common_window.inc
- scripts/rockSaw.lua
- scripts/veggies_semiAuto.lua
Missing "message" variable was breaking the macro - fixed
> Rocksaw fix

- scripts/rockSaw.lua
Github tried to be helpful and ended up reverting back to the old rockSaw.lua, this is the new version again :D
> Fixed rockSaw.lua

- scripts/statclicks.lua
> statclicks - Dig Hole fix

- scripts/gather_resources.lua
Timing increase - should correctly move in both directions now, rather than skipping every 2nd click.
> Improvement to the auto movement timer

- scripts/gather_resources.lua
The previous update accidently added a delay that causes poor results when gathering slate, this is the fix.
> Fixing a delay

- scripts/CarpentryShop.lua
Macro for making boards on a carpshop.
> CarpShop Boards by Anien

- scripts/saltWater.lua
Gathers saltwater, tags each tub, hits hotkey X over each tag to evaporate salt water, waits 21 minutes.... repeats
> saltWater.lua

- scripts/statclicks.lua
Added repair function to the flax comb and hackling rake macros within statclicks, also added formatting to the code so that it is more readable.
> Repair flax comb

- scripts/statclicks.lua
I broke statclicks with bad code for eating onions when the buff is not already active, this is the fix :D
> Eating onions fix

- scripts/common_ui.inc
- scripts/screen_reader_common.inc
Removed the settings information at the top of the automato window that informs users they should try putting the game in High Priority mode, as this feature is gone.
> High Priority info removed

- scripts/stoneCutting.lua
stoneCutting up date - fixed refresh click to cover masons bench
> Refresh window fix

- scripts/saltWater.lua
drawWater function was called in the wrong place
> Minor fix for gathering saltwater

- scripts/forge_auto.lua
Fixed the chat window scrolling bug
> Chat window clicking fix

- scripts/stoneCutting.lua
Increased the window spacing and a slight increase on the timer for cutting stones to compensate for server lag.
> Increased spacing and timer

- scripts/mining_ore.lua
Added Cobalt and removed Lithium, Titanium, Strontium and Tungsten
> Added and Removed Ores

- scripts/bricks.lua
Bricks v2.0 - Now supports both automatic and hotkey modes
> Major bricks.lua update

- scripts/bricks.lua
Renamed "Automatic mode" to "Grid mode"
> Renamed mode

- scripts/flax_stable.lua
Wrapped "walkHome" in a "readClock" if statement so it wont get read if "Read Clock Coords" is unchecked.
> Clock check added around 'walkHome'

- scripts/common_click.inc
- scripts/flax_stable.lua
Added auto gather water and auto rot functionality.
> Auto Rot functionality

- scripts/statclicks.lua
Small script added to the endurance options to repeatedly gather water and empty jugs to test gathering water insects from a single location. This needs a lot more testing than I can do solo, will remove if it turns out to be useless.
> Water Insects

- scripts/flax_stable.lua
Fixed a bad local call for 'startPos' within doit()
> Fixed bad 'local' declaration

- scripts/veg_janitor/plant.inc
Use the config instead of a hardcoded number 3!
> Fix 4 stage plants in veg_janitor

- scripts/kettle_full.lua
- scripts/thermometer.lua
Adding changes made by Ashen to the themometer and kettle macros since I broke his pull request with a merge conflict :(
> Thermo and Kettle updates

- scripts/statclicks.lua
Added carving Rawhide Strips to statclicks focus options
> Rawhide Strips

- scripts/forgeItems.txt
Added Mouldboard to the list of items that can be made on the forge_auto macro.
> Added Mouldboard

- scripts/flax_stable.lua
Added a checkbox option to allow the user to specify that they want the grid to start being positioned below the top UI bar.
> New option added

- scripts/gather.lua
Fix for collecting slate with gather.lua
> fix for gathering slate

- scripts/gather.lua
Updated the colour for detecting the wh so it now stashes correctly.
> WH colour updated for stashing

- scripts/stoneCutting.lua
Major script refactor to no longer be effected by current levels of server latency.
> Script refactor to not depend on server lag

- scripts/stoneCutting.lua
Added 'Take --> Everything' and removed some debugging
> Removing debugging from status message

- scripts/kiln.lua
> Adding kiln.lua

- scripts/mining_ore.lua
Modified the key combination for reseting the mining_ore script to be Ctrl+Alt instead of the original Shift
> Modified reset function

- scripts/mining_gems.lua
Updated mining_gems to change the reset to menu key combination to Ctrl + Alt so it is aligned with mining_ore.
> Updated reset function

- scripts/freeChariot.lua
> Free chariot script

- scripts/wttt_k_values.lua
Porting the wood treatment tank k values script from T8 over to the new repo.
> Adding wttt_k_values.lua

- scripts/paint_mix.lua
Only needed + button image filename changed to port from T8.
> Added paint_mix.lua.

- scripts/statclicks.lua
Adding Pyramid Block Pushing back into statclicks
> Push Pyramid Blocks

- scripts/wttt_k_values.lua
> wtt_k_values

- scripts/wttt_k_values.lua
Fixed the k value calculation done after testing
> Fixed value calculation

- scripts/ToxinKitchen.lua
- scripts/autorun.lua
ToxinKitchen.lua: Added recipe for Cloudy solvents.
autorun.lua: Add "Eat this mushroom" and "Pick up the" (mushroom) to auto-click activities to so picking mushrooms can once again be single-click since addition of option to cultivate spores.
> autorun.lua and ToxinKitchen.lua enhancements

- scripts/forgeItems.txt
Left Star Metal in as people have got it from snow storms, so seems it was not removed.
> Updated list of forge items

- scripts/raeli_color_mon.lua
> Raeli Colour Monitor

- scripts/gather.lua
- scripts/paint_mix.lua
This fixes an issue where gather.lua did not fill jugs correctly. Also, an issue where asking for 100db of paint would do 10 batches of 10 rather than one of 100
> Minor fixes

- scripts/essences.lua
> Removed a sleepWithStatus that was for testing

- scripts/essences.lua
> Missed the word 'tree' from 1 resin type

- scripts/stoneCutting.lua
- scripts/watermine.lua
Minor tweaks to stonecutting and watermine
> Minor tweaks

- scripts/chem_helper.lua
> chem_helper.lua - Updated with new resins

- scripts/gather.lua
jugless gathering added as an option to gather.lua
> Added 'jugless gathering' option

- scripts/chem_helper.lua
- scripts/chem_helper_cheap.lua
- scripts/kiln.lua
- scripts/woodTreatment.lua
Some minor updates for several scripts
> Minor updates

- scripts/chem-cheap.txt
Chem-cheap recipe typo fixes and recipe updates
> Typo fixes

- scripts/crematory.lua
- scripts/kiln.lua
- scripts/potteryAuto.lua
- scripts/simon.lua
Minor bug causing the settings files to be ignored on script load meant that pass counts persisted across all scripts.
> Pass count persistance error fix

- scripts/metalTreatment.lua
- scripts/paint_mix.lua
- scripts/woodTreatment.lua
Facelifts for wood and metal treatment and window detection fixes
> Facelifts and window detection fixes

- scripts/mining_ore.lua
- scripts/paint_mix.lua
Missing "local skipWork = nil;" meant that if a node was broken during mining, the script had to be re-started otherwise further loops would not continue to mine.
> Major bug fix - variable reset

- scripts/incense_tracker.lua
> Adding mushroom support

- scripts/chem-cheap.txt
Replaced a broken "Ra,As+++++,Sw-----" recipe with one that works :)
> Fixed a broken recipe

- scripts/castingItems.txt
- scripts/forge_auto.lua
Added medium gear support and missing metals - Moon Steel, Thoth's Metal and Water Metal.
> Added medium gear x1 & x10 support

- scripts/mining_ore.lua
Minor update to the Dual Screen mining option - It will now clean up the windows it opens while dual screen mining for you, instead of leaving you with a game screen full of mining node windows once complete!
> Dual Screen mining - minor update

- scripts/metalTreatment.lua
Added an additional 1 second at the end of the macro to allow for server lag to let the Chemical Bath reset.
Also added an additional check to validate that the "Metal in Bath" value is set to "None"
> Timer and validation

- scripts/VineTender.lua
Fixed issue with additional clicks taking place after closing out the vineyard window that had been tended.
> Vinetender window fix + Facelift

- scripts/statclicks.lua
Added "Search Rotten Wood" to the focus timer on statclicks, allowing players who have the right Salvage Techniques level to recycle rotten wood :)
> Search for Bugs

- scripts/forge_auto.lua
Fixed a conflicting global declaration of makeBox which was causing the forge_auto macro to fail making several items.
> Fix conflicting declaration

- scripts/gather.lua
gather.lua will now always stash items if you pin the warehouse window if the window is not pinned it will still search for a warehouse using the previous pixel detection system and it now has papyrus in it, so you can make automatic papyrus routes.
> Added Papyrus and Warehouse fix

- scripts/paint_mix.lua
Fixed an issue that would not let you make less than 50 silk ribbons at a time, due to the automatic selection of batch sizing.
> Make Coloured Ribbon

- scripts/ToxinKitchen.lua
The toxin kitchen macro will now auto scroll for you, when selecting Renenutet's Solvent.
> Added Renenutets Solvent Capability

- scripts/flax_stable.lua
Reduced the walk distance between plantings, to create a tighter grid, to remove the issue with walking south produced by the new UI.
> Tighter flax grid

- scripts/chem-cheap.txt
> chem recipes update

- scripts/chem_extract_auto.lua
- scripts/chem_notepad.lua
- scripts/wttt_k_values.lua
The wood treatment k value macro no longer cares about how many lines are building header, so it's more reliable
The chem extract macro now sorts data on import, and requirements before searching, so that recipes are always found regardless of order
> Improve Wood Treatment K-Values and Fix Chem Extract Auto

- scripts/chem-cheap.txt
Bunch of new cheap recipes courtesy of Lazybum (who is suspiciously productive)
Looks like my IDE also fixed the line endings in the file. I suggest viewing the diff with whitespace filtered
> Adding cheap extract recipes from Lazybum

- scripts/treat_yo_self.lua
This macro works without having recipes or measuring k-values.
> A new treatment macro that assists with both wood and metal treatments

- scripts/treat_yo_self.lua
Fix bug in final treatment timing.
Add a button to return to the goals menu.
> Improvements to Treat Yo Self

- scripts/flax_stable.lua
to keep it out of the way of movement
> Close the bottom icon tray while planting flax

- scripts/moss_blessings.lua
It also logs moss attribute changes
> Simple new macro for blessing Aqueduct towers,
