scripts/rockSaw.lua
Rocksaw wording changes to 'This Rock Saw' rather than 'This is' - updated the clickAllText accordingly to correctly refresh the window at the end of each pass.
=> Refresh window fix

scripts/window_manager.lua
Slight increase on the spacing between windows when using window manager to make sure they dont overlap to avoid miss clicking.
=> Spacing fix

scripts/potteryAuto.lua
BUGFIX: Spacing increase to avoid overlapping windows not being clicked
=> Spacing increase

scripts/potteryAuto.lua
The timer was off on moulding jugs on a pottery wheel in live so it would skip every 2nd pass.
=> Pottery Wheel - More accurate timer on moulding jugs

scripts/common_window.inc, scripts/veggies_semiAuto.lua
Added a checkbox option to allow the user to select to start planting the grid below the top UI bar, as with the bars expanded it will often miss click and do strange things like open the players inventory.
=> Veggie_SemiAuto - Added function to start the grid below the UI

scripts/gather_resources.lua
"lastGathered = lsGetTimer()" was missed from line 56, meaning that grass picking would fail 100% of the time after 10 seconds had passed. (Approx 3 picking actions)
=> Missing line of code

scripts/flax_stable_noClock.lua
Looks like the code that handles the different window sizes for when guilded... "Useable By...." was removed, this is re-adding it in :)
=> Re-added the code to deal with guilded window size

scripts/statclicks.lua
Switched to FindText for auto eating onions while using statclicks.lua to stop the script freezing if the text is not visible at any point.
=> Better method for finding 'Eat some' text

scripts/cc_Auto.lua
Added a 0.5 second increase to the time between checks on cc_Auto as the wood consumption was far too high for the output
=> Slight timer increase

scripts/forgeItems.txt
Extrusion plates where showing in automato as requiring 40 Iron when they require Copper.
=> Incorrect metal requirement

scripts/saltWater.lua
Reduced the timer on refilling a tub with saltwater by 1 minute as per the changelog in game whereby its better to refill before it emptys than wait for 1 full "use"
=> Timer tweak

scripts/potteryAuto.lua
Increased the window spacing to compensate for the wheel already having an item on it when the started.
=> Fixed window spacing

scripts/.luacheckrc, scripts/flax_stable.lua
Correctly reset 'rot_flax' and 'water_needed' back to false if the readClock option is unchecked.
=> Correctly set walkTo options

scripts/gather.lua
Added 23 new trees for T9. 
Tweaked warehouse colors to avoid conflicts with icon borders, tool benches, etc.
Added note to enable fast gather from trees.
=> T9 trees and colors for gather.lua

scripts/kettle_full.lua
Slight increase on the window spacing for kettle windows, they should no longer overlap causing the macro to fail at taking the product and get stuck in an endless loop.
=> Improved window spacing

scripts/mining_ore.lua
* Don't bother trying to find 4-stone combos if there were fewer than four 3-stone combos, since there won't be one. (Saves a couple seconds of wasted time checking).
* Restore use of equalsets() function to compare tables. Turns out == operator does not compare table contents/values as one would expect, so that suggested optimization won't work.
=> 4-stone combo fixes:

scripts/ToxinKitchen.lua
Dark red matching may not be working properly anymore with T9, causing it to try to start a toxin batch before con timer is ready (i.e. bright red).
=> ToxinKitchen.lua: only allow white Constitution, not dark red, before starting.

scripts/essences.lua
For some reason, within the item selection menu popup, the OCR is reading capital F as a lower case L so for the time being I have replaced to use of "F" with "l" in the resin array, please do not change it back until we fix the OCR.
=> Workaround for ocr reading F

scripts/paint_common.inc
Missing screenread, caused the loop to fail the 2nd time around with "no buttons found"
=> paint_common fix

scripts/flax_stable.lua, scripts/saltWater.lua, scripts/stoneCutting.lua
Minor bug causing the settings files to be ignored on script load meant that pass counts persisted across all scripts.
=> Pass count persistance error fix

scripts/barrelVise.lua
barrelVise now shows the correct volume of materials required depending on how many barrels are being processed, rather than just the base materials per barrel.
=> Correct material count

scripts/forge_auto.lua
This macro would often fail when trying to find items burried within child windows, I have updated the click positions so this no longer happens, although it has had limited testing, so will revert if it does not work for others.
=> Updated clicks

scripts/statclicks.lua
Removed the hard coded value "stirMaster = false" and added a checkbox to allow users to select if they want to auto fill the clinker vat when stiring cement.
=> Automatic vat filling - stiring cement

scripts/forge_auto.lua
Fixed making bulk gears and re-added the EXACT flag to bars to compensate for making bars where names cross over.
e.g. Steel Bars vs Moon Steel Bars
=> Re-added EXACT flag for minor bugfix

scripts/paint_mix.lua
This was reading the whole screen, which meant that it detected the + icon on the map window and if there was any + symbols in the chat box which then causes the paint macro to miss click and not produce paint correctly.
I've added a boundry for it to search within for the + icon, so that should no longer happen.
=> Reduced scanning radius

scripts/paint_common.inc, scripts/paint_mix.lua, scripts/paint_watch.lua
close_map() is now a redundant function as I have added a scan boundary on the pigment lab so I have removed it from paint_mix and paint_watch.
paint_watch was not counting clicks correctly, which meant it was always using -1 the amount of Red Sand required to reset the lab correctly.
=> Scan Boundary, Additional Reset Clicks

scripts/kiln.lua, scripts/thermometer.lua
* Utilize clickAllText when text is kiln-specific, to avoid needing to process each region individually.
* Stop using clickAllText when taking from the kiln, and loop over each kiln region, so that it won't empty other pinned windows
* Take everything from kilns prior to starting passes
* Reorder kilns drop down to put Vault kiln at the bottom.
* Fix whitespace
* Also fixing the thermometer script for the final polish skill
=> Make the kiln macro safe to run in parallel with other macros.
